Videos/podcast outline
jgrgurovic/ProficoAcademy_pet_project pull request #13
Opened 2023-09-10 17:56 UTC by jgrgurovic

2023-09-10 20:55 UTC, ilovric00 commented
@jgrgurovic build is failing

2023-09-10 20:56 UTC, ilovric00 requested changes
This PR contains some part from other PR. 

Let me explain you tomorrow how you should handle this.

2023-09-10 22:24 UTC, jgrgurovic commented
> @jgrgurovic build is failing
Wrong path for hero image, build is fine now

2023-09-10 22:25 UTC, jgrgurovic commented
> This PR contains some part from other PR.
> 
> Let me explain you tomorrow how you should handle this.
It got somehow mixed with the Login one , not sure how or why but sure we'll see tomorrow

2023-09-15 20:06 UTC, ilovric00 approved these changes

2023-09-15 20:06 UTC, ilovric00 commented on package.json
> +    "react-icons": "^4.11.0",
I think this is an overkill to you external lib just for the handling the icons

2023-09-15 20:06 UTC, ilovric00 commented on views/HeroSection/index.tsx
> +}
move this to `utils/static` folder

2023-09-15 20:06 UTC, ilovric00 commented on views/Search&FilterSection/SearchBar.tsx
> +const SearchBar = () => {
missing space before and after...do you use Prettier?

2023-09-21 23:50 UTC, merged